[2024-05-10T16:42:18.547+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-10T16:42:18.773+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag_v3.task2 scheduled__2024-05-09T00:00:00+00:00 [queued]>
[2024-05-10T16:42:18.822+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag_v3.task2 scheduled__2024-05-09T00:00:00+00:00 [queued]>
[2024-05-10T16:42:18.828+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 7
[2024-05-10T16:42:18.935+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): task2> on 2024-05-09 00:00:00+00:00
[2024-05-10T16:42:18.955+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag_v3', 'task2', 'scheduled__2024-05-09T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpu2s613zw']
[2024-05-10T16:42:18.966+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask task2
[2024-05-10T16:42:18.969+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=742) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-10T16:42:18.976+0000] {standard_task_runner.py:63} INFO - Started process 749 to run task
[2024-05-10T16:42:19.174+0000] {task_command.py:426} INFO - Running <TaskInstance: my_first_dag_v3.task2 scheduled__2024-05-09T00:00:00+00:00 [running]> on host 48bfb4afd9cd
[2024-05-10T16:42:19.456+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='edo' AIRFLOW_CTX_DAG_ID='my_first_dag_v3' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-09T00:00:00+00:00'
[2024-05-10T16:42:19.458+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-10T16:42:19.497+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-10T16:42:19.500+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo second one matey']
[2024-05-10T16:42:19.518+0000] {subprocess.py:86} INFO - Output:
[2024-05-10T16:42:19.523+0000] {subprocess.py:93} INFO - second one matey
[2024-05-10T16:42:19.524+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-10T16:42:19.527+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-10T16:42:19.571+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=my_first_dag_v3, task_id=task2, run_id=scheduled__2024-05-09T00:00:00+00:00, execution_date=20240509T000000, start_date=20240510T164218, end_date=20240510T164219
[2024-05-10T16:42:19.640+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-10T16:42:19.700+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-10T16:42:19.706+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
