[2024-05-11T10:13:51.177+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-11T10:13:51.452+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag_v4.task3 scheduled__2024-05-10T00:00:00+00:00 [queued]>
[2024-05-11T10:13:51.570+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag_v4.task3 scheduled__2024-05-10T00:00:00+00:00 [queued]>
[2024-05-11T10:13:51.574+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-11T10:13:51.759+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): task3> on 2024-05-10 00:00:00+00:00
[2024-05-11T10:13:52.373+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=8424) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-11T10:13:52.385+0000] {standard_task_runner.py:63} INFO - Started process 8427 to run task
[2024-05-11T10:13:52.318+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag_v4', 'task3', 'scheduled__2024-05-10T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmp0bjqe9qo']
[2024-05-11T10:13:52.386+0000] {standard_task_runner.py:91} INFO - Job 30: Subtask task3
[2024-05-11T10:13:53.121+0000] {task_command.py:426} INFO - Running <TaskInstance: my_first_dag_v4.task3 scheduled__2024-05-10T00:00:00+00:00 [running]> on host 48bfb4afd9cd
[2024-05-11T10:13:54.506+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='edo' AIRFLOW_CTX_DAG_ID='my_first_dag_v4' AIRFLOW_CTX_TASK_ID='task3' AIRFLOW_CTX_EXECUTION_DATE='2024-05-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-10T00:00:00+00:00'
[2024-05-11T10:13:54.518+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-11T10:13:54.610+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-11T10:13:54.620+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo third one matey']
[2024-05-11T10:13:54.708+0000] {subprocess.py:86} INFO - Output:
[2024-05-11T10:13:54.720+0000] {subprocess.py:93} INFO - third one matey
[2024-05-11T10:13:54.723+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-11T10:13:54.739+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-11T10:13:55.110+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=my_first_dag_v4, task_id=task3, run_id=scheduled__2024-05-10T00:00:00+00:00, execution_date=20240510T000000, start_date=20240511T101351, end_date=20240511T101355
[2024-05-11T10:13:55.274+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-11T10:13:55.944+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-11T10:13:55.959+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
